In [18]:
import numpy as np

In [19]:
before=np.array([[[1,2,3,4],[5,6,7,8]]])
print(before)
after=before.reshape(2,2,2)
print(after)


[[[1 2 3 4]
  [5 6 7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# verically stack
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
# Horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
h1,h2

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.]]))

In [22]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [23]:
filedata=np.genfromtxt('file.txt',delimiter=',',dtype='int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [26]:
a=filedata[filedata>50]
a

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [32]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])