In [125]:
import numpy as np

In [126]:
ar = np.array([1, 2, 3, 4])

In [127]:
ar_2 = np.array([[1,2,3,4,5,6,7],
                 [8, 9, 10,11,12,13,14]])
ar_2


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [128]:
#columns
ar_2[:,1]

array([2, 9])

In [129]:
#Rows
ar_2[1:,]

array([[ 8,  9, 10, 11, 12, 13, 14]])

In [130]:
ar_2[0,1:6:2]

array([2, 4, 6])

In [131]:
ar_2[1,5]=20

In [132]:
ar_2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [133]:
ar_2[:,2]=[1,2]
ar_2

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [134]:
b = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
              [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
              [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])



https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/
3D
The first index, i, selects the matrix
The second index, j, selects the row
The third index, k, selects the column

In [135]:
# b[i,r,c]
b[:,:,0]


array([[10, 13, 16],
       [20, 23, 26],
       [30, 33, 36]])

In [136]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [137]:
ar_2.shape

(2, 7)

In [138]:
np.full(ar_2.shape,45)

array([[45, 45, 45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45, 45, 45]])

In [139]:
np.full_like(ar_2,55)

array([[55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55]])

In [140]:
#random decimal Number
np.random.rand(2,3)

array([[0.81356025, 0.40743393, 0.73647165],
       [0.65059747, 0.08790788, 0.70528445]])

In [141]:
np.random.rand(3,2,2)

array([[[0.49524728, 0.33197334],
        [0.81344798, 0.33040635]],

       [[0.52553075, 0.16966403],
        [0.96609737, 0.28465444]],

       [[0.99351487, 0.23760901],
        [0.34162071, 0.95033918]]])

In [142]:
np.random.random_sample(ar_2.shape)

array([[0.52393689, 0.15620516, 0.70736899, 0.8146631 , 0.56572696,
        0.35123849, 0.45466174],
       [0.34471945, 0.75376257, 0.04329884, 0.94356977, 0.33607915,
        0.8112968 , 0.07384797]])

In [143]:
np.random.randint(1,7,size=(2,3))

array([[1, 5, 2],
       [6, 4, 1]])

In [144]:
#identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [145]:
ar=np.array([[1,2,3]])
r1=np.repeat(ar,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [146]:
#to Make
a =[[1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 9, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1]]


In [147]:
m = np.ones((5, 5),dtype='int32')
print(m)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [148]:
n=np.zeros((3,3),dtype='int32')
print(n)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [149]:
n[1,1]=9
print(n)

[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [150]:
m[1:4,1:4]=n
m

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [158]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [161]:
a*=2
print(a)


[ 4  8 12 16]


In [176]:
a=np.ones((2,3),dtype='int32')
b = np.full((3, 2), 2, dtype='int32')
a,b


(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[2, 2],
        [2, 2],
        [2, 2]]))

In [179]:
c=np.matmul(a,b)
print(c)

[[6 6]
 [6 6]]


In [188]:
d=np.linalg.det(c.astype(int))
print(int(d))

0
